spring:
  application:
    name: hystrix-turbine
server:
  port: 8031
security:
  basic:
    enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: airparking-user
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/